olive_app/urls.py
"""olive_app URL Configuration
"""
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
  path('admin/', admin.site.urls),
  path('', TemplateView.as_view(template_name='home.html'), name='home'),
  path('users/', include('users.urls', namespace='users'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
"""olive_app URL Configuration
"""
from django.conf import settings
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView


from users.views import signup,ProfilePage,activate,change_password,DashBoardPage,MembersList,DashBoardRedirect

app_name='users'
urlpatterns = [
  path('login/', auth_views.LoginView.as_view(template_name= 'users/login.html'), name='user_login'),
  path('logout/', auth_views.LogoutView.as_view(template_name= 'users/logged_out.html'), name='user_logout'),
  path('signup/', signup, name='signup_user'),

  path('profile/<str:username>', ProfilePage, name='user_profile'),
  path('', DashBoardRedirect, name='dashboardredirect'),
  path('dashboard/', DashBoardPage, name='dashboard'),
  path('members/', MembersList, name='members'),

  path('activate/<uidb64>/<token>/activate', activate, name='activate'),
  path('activations_sent', TemplateView.as_view(template_name='users/account_activation_sent.html'), name='account_activation_sent'),

  path('change-password', change_password, name='change_password'),
  path('password_reset', auth_views.PasswordResetView.as_view(template_name= 'users/password_reset_form.html', email_template_name='users/password_reset_email.html', \
    subject_template_name='users/password_reset_subject.txt', success_url = reverse_lazy('users:password_reset_done')), name='password_reset'),
  path('password_reset/done', auth_views.PasswordResetDoneView.as_view(template_name= 'users/password_reset_done.html'), name='password_reset_done'),
  path('reset/<uidb64>/<token>/reset',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
  path('reset/done', auth_views.PasswordResetCompleteView.as_view(template_name= 'users/password_reset_complete.html'), name='password_reset_complete'),

]

users/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import pre_save, post_save
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from phone_field import PhoneField
from django_countries.fields import CountryField

''' GENDER CHOICES '''
GENDER_CHOICES = (
  ("", ""),
  ("Male", "Male"),
  ("Female", "Female"),
)
choices = GENDER_CHOICES

class UserProfile(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
  location = models.CharField(max_length=200, default='')
  status_word = models.CharField(max_length=30, default='')
  bio = models.TextField(max_length=500, default='')
  position = models.CharField(max_length=50, default='')
  gender = models.CharField(max_length=50, default='', choices = GENDER_CHOICES)
  date_of_birth = models.DateField(verbose_name=_("Birthday"), null=True)
  country = CountryField(blank_label='(select country)')
  address = models.CharField(max_length=300, default='')
  postal_code = models.CharField(max_length=10, default='')
  phone = PhoneField(blank=True, help_text='Enter phone number')
  profile_photo = models.ImageField(_("Profile Photo"), upload_to='media_house', height_field=None, width_field=None, max_length=None, default='')
  email_confirmed = models.BooleanField(default=False)
  def __str__(self):
      return self.user.username

  def __unicode__(self):
      return self.user.username

  @property
  def get_photo_url(self):
      if self.profile_photo and hasattr(self.profile_photo, 'url'):
          return self.profile_photo.url
      else:
          return "/static/images/dummy-avatar.jpg"

''' Signal Fired After  User Created '''
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.get_or_create(user=instance)
        # PricingPerSMSPerUserToPurchase.objects.get_or_create(user=instance)
        # BonusAccount.objects.get_or_create(user=instance)
    # instance.userprofile.save()
    # instance.user_profile.save()
    # instance.smspricingperuser.save()
    # instance.user_bonus.save()

users/forms.py
from django import forms
from .models import UserProfile
# from smsangonumcredit.models import NumberCredits
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField
# from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import *
User = get_user_model()
from django_countries.widgets import CountrySelectWidget


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
          'first_name',
          'last_name',
        ]

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = [
          'location',
          'status_word',
          'bio',
          'position',
          'address',
          'gender',
          'date_of_birth',
          'profile_photo',
          'phone',
          'country',
          'postal_code',
        ]
        widgets = {
            'date_of_birth':forms.DateInput(attrs={'type':'date'}),
            'profile_photo':forms.ClearableFileInput(attrs={'type': 'file'}),
            'phone':forms.NumberInput(attrs={'type': 'number', 'placeholder':'2348100001111', 'min':'2347000000000','max':'2349999999999'}),
            'country': CountrySelectWidget(),
            'postal_code': forms.NumberInput(attrs={'type': 'number', 'placeholder':'100001'}),
            'address': forms.TextInput(attrs={'maxlength':300, 'required':False, 'placeholder':'Address'}),
            'gender': forms.Select(choices=GENDER_CHOICES),
            'bio': forms.Textarea(attrs={'maxlength':500}),
            'status_word': forms.TextInput(attrs={'maxlength':50, 'required':False, 'placeholder':'Watch word'}),
            'location': forms.TextInput(attrs={'maxlength':50, 'required':False, 'placeholder':'Location'}),
            'position': forms.TextInput(attrs={'maxlength':50, 'required':False, 'placeholder':'Position'}),
        }


class SignUpForm(UserCreationForm):
    #first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    username = forms.CharField(max_length=30, required=True, help_text='Required. Unique username')
    email = forms.EmailField(max_length=254, required=True, help_text='Required. Inform a valid email address.')
    class Meta:
        model = User
        fields = ('username','email','password1', 'password2' )

    def clean_email(self):
        # Get the email
        email = self.cleaned_data.get('email')
        match = User.objects.filter(email=email)
        
        if match:
	        raise forms.ValidationError('This email address is already in use.')
        else:
        	return email   

users/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.validators import RegexValidator
from django.db.models import Q
from django.template.loader import render_to_string
from django.db import IntegrityError, transaction
import random
from .tokens import account_activation_token
from django.utils.encoding import force_bytes, force_text, smart_text 
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils import timezone
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect 
from django.contrib.auth.models import User
from .forms import ProfileUpdateForm, UserProfile, SignUpForm, UserUpdateForm
from coreconfig import tasks

def signup(request):
  form = SignUpForm()
  context	= {
    'register_form': form,
  }
  if request.method == 'POST':
    form = SignUpForm(request.POST)
    if form.is_valid():
      user = form.save(commit=False)
      user.is_active = True
      user.save()
      current_site = get_current_site(request)
      uid = urlsafe_base64_encode(force_bytes(user.pk))
      print(uid)
      # if len(config) == 0:
      subject = 'Activate SiteName'
      message = render_to_string('users/account_activation_email.html',{
        'username': user.username,'domain': current_site.domain,'uid': uid,'token': account_activation_token.make_token(user),
      })
      tasks.sending_mail(subject, message, user.email)
      # else:
      #   subject = 'Activate Your SiteName Account'
      #   message = render_to_string('users/account_activation_email.html',{
      #     'username': user.username,'domain': current_site.domain,'uid': uid,'token': account_activation_token.make_token(user),
      #   })
      #   tasks.sending_mail(subject, message, user.email)
      return redirect('users:account_activation_sent')
  else:
    return render(request, 'users/register.html', context)
  return render(request, 'users/register.html', context)

def activate(request, uidb64, token):
    try:
    	uid = force_text(urlsafe_base64_decode(uidb64))
    	user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, UserModel.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):    	
        user.is_active = True
        user.save()
        user.user_profile.email_confirmed = True
        user.user_profile.save()
        current_site = get_current_site(request)
        config = []#DashboardConfig.objects.all()
        if len(config) == 0:
	        subject = 'Your Account is Activated'
	        message = render_to_string('users/account_activation_email_followup.html', {
	        	'username': user.username,
	        	'domain': current_site.domain,
	        	})
	        tasks.sending_mail(subject, message, user.email)
        else:
	        subject = 'Your Account is Activated'
	        message = render_to_string('users/account_activation_email_followup.html', {
	        	'username': user.username,
	        	'domain': current_site.domain,
	        	})
	        tasks.sending_mail(subject, message, user.email)
		##############################################
        user.backend = 'django.contrib.auth.backends.ModelBackend'
        login(request, user)
        return HttpResponseRedirect('/users/dashboard')
    else:
        return render(request, 'users/account_activation_invalid.html')

def get_absolute_url(self):
		return reverse('users:activate')

@login_required(login_url='/users/login')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('users:change_password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'users/change_password.html', {
        'form': form
    })


def LoginView(request):
	return render(request, 'users/login.html', {})

def ProfilePage(request, username):
  # username = username.split('@')
  context=''
  user = request.user
  getUser = get_object_or_404(User, username=username.lower())
  getUserProfile = UserProfile.objects.get(user=getUser)
  profileForm = ProfileUpdateForm(instance=getUserProfile)
  userExtended = UserUpdateForm(instance=getUser)
  if request.method == 'POST':
    profileForm = ProfileUpdateForm(request.POST, request.FILES, instance=getUserProfile)
    userForm = UserUpdateForm(request.POST, instance=getUser)
    if profileForm.is_valid() and userForm.is_valid():
      userEx = userForm.save(commit=False)
      userProfile = profileForm.save(commit=False)
      print(userProfile.location)
      userEx = userEx.save()
      userProfile = profileForm.save()

      print('done')
  if user == getUserProfile.user:
    context = {
      "profileForm": profileForm,
      "userExtended": userExtended,
      "getUserProfile":getUserProfile,
      "user":user
    }
  else:
    context = {
      "profileForm": profileForm,
      "userExtended": userExtended,
      "getUserProfile":getUserProfile,
      "user":getUserProfile.user
    }
  return render(request, 'users/profile.html', context)

# def ProfileUpdateForm(request)

def DashBoardPage(request):
  return render(request, 'users/dashboard.html', {})

def DashBoardRedirect(request):
  return redirect('users:dashboard')

def MembersList(request):
  user = request.user
  members = User.objects.all().exclude(pk=user.id)
  return render(request, 'users/dashboard.html', {'members':members})

olive_app/templates/users/account_activation_email.html
{% autoescape off %}
<p>Hi {{ username }}, <br/></p>

<p>Thanks for Registering on {{ domain }} !!! <br/></p>

<p> Copy and Paste the link below in your browser to confirm your registration: <br/></p>

<a href="{{ domain }}/users/activate/{{ uid }}/{{ token }}/activate">{{ domain }}/users/activate/{{ uid }}/{{ token }}/activate</a> <br/>


<p>If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead. <br/></p>

<p>Enjoy the Experience and Reffer your Friends and Family. <br/></p>

<p>Best Regards <br/>{{domain}}</p>
{% endautoescape %}

olive_app/templates/users/account_activation_email_followup.html
{% autoescape off %}
<p>
Hi {{ user.username }},

Your account is now activated

</p>


{% endautoescape %}

olive_app/templates/users/account_activation_invalid.html
{% load static bootstrap4 %} {# Display django.contrib.messages as Bootstrap alerts #}
{% comment %}
  {% load dashboardconfig %}
{% DashboardConfigs as config %}
{% endcomment %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}{% block title %} Invalid Activation {% endblock %} {% block head_block %} {% endblock %} 

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Invalid Activation Code</h3>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

olive_app/templates/users/account_activation_sent.html
{% load static bootstrap4 %} {# Display django.contrib.messages as Bootstrap alerts #}
{% comment %}
  {% load dashboardconfig %}
{% DashboardConfigs as config %}
{% endcomment %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}{% block title %} Activation Sent {% endblock %} {% block head_block %} {% endblock %}

{% block content %}

 <div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-6 col-lg-6 col-md-6">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-12">
                <div class="p-5">
                  <div class="text-center">
                    <a href="/"><img src="{% if config.site_logo %} {{config.site_logo}} {% endif %}" alt="{{config.site_name}}" title="{{config.site_name}}" width="30%"></a>
                  </div>
                  <hr>
                  <div class="text-center">
                  	Please Check Your Mail (Inbox or Spam) For Activation link
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

{% endblock %}

olive_app/templates/users/login.html
{% extends 'users/base_accounts.html' %}
{% load static bootstrap4 %}

{% comment %}
  {% load dashboardconfig %}
{% DashboardConfigs as config %}
{% endcomment %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{% block title %}  Login {% endblock %}
{% block content %}
<style>
  .card{
    background-color: #ffffff00!important;
  }
  input.form-control {
    display: block;
    width: 100%;
    padding: .375rem .75rem;
    font-size: 1rem;
    line-height: 1.5;
    color: #495057;
    background-color: #fff!important;
    background-clip: padding-box;
    border: 0px!important;
    border-radius: .5rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}
input[type=text]{
    background-color: #ffffff!important;
}
/* #myelement {
  position: relative;
  overflow: hidden;
  transform: rotate(30deg);
}

#myelement::before {
  content: "";
  position: absolute;
  width: 200%;
  height: 200%;
  top: -50%;
  left: -50%;
  z-index: -1;
    transform: rotate(-30deg);

  /*background: url({% static 'images/purple.png' %}) 0 0 no-repeat;*/
  /*style="background-image:url({% static 'images/purple.png' %}); background-position:center center; background-size:cover"
  }*/

#ele{
  /*background-image:url({% static 'images/new-design-1.png' %});*/ 
  /*background-position:center center; */
  /*background-size:cover;*/
  /*-webkit-animation: rotation 2s infinite linear;*/

}

@-webkit-keyframes rotation {
  from {
      -webkit-transform: rotate(0deg);
  }
  to {
      -webkit-transform: rotate(359deg);
  }
}

.centered {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
 .ele{
  background-image:url({% static 'images/bigger-new-design.png' %}); 
  background-position:center center; 
  background-size: cover; 
  height: 100vh;
}
/*@media only screen and (max-width: 720px) and (orientation: portrait) {

  .ele{
    background-image:url({% static 'images/bigger-new-design.png' %}); 
    background-position:center center; 
    background-size: auto!important;
  }
}
@media only screen and (max-width: 812px) and (orientation: landscape) {

  .ele{
    background-image:url({% static 'images/new-design-1.png' %}); 
    background-position:center center; 
    background-size: auto!important;
  }
} */

</style>
<div class="ele">
  <div class="container centered">

    <!-- Outer Row -->
    <div class="row justify-content-center">
      <!-- <img src="{% static 'images/redesign-BACKGROUND.png' %}" alt="" style="width:100%;"> -->
        <div class="actions col-lg-5 col-md-5">
          <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0 ">
              <!-- Nested Row within Card Body -->
              <!-- <div class="row" > -->
                <div class="col-lg-12" id="ele">
                  <div class="p-5">
                    <div class="text-center">
                      <!-- {% if config.site_logo %}<a href="/"><img src="{{config.site_logo.url}}" alt="{{config.site_name}}" title="{{config.site_name}}" width="30%"></a>{% endif %} -->
                      <h1 class="h4 text-white mb-4">Welcome</h1>
                    </div>
                    <form id="mainForm" class="user" role="form" method="post">
                      {% csrf_token %}                        
                        {% bootstrap_form form %}
                      {% buttons %}
                      <div class="form-group">
                        <div class="custom-control custom-checkbox small">
                          <input type="checkbox" class="custom-control-input" id="customCheck">
                          <label class="custom-control-label" for="customCheck">Remember Me</label>
                        </div>
                      </div>
                      <button id="submit" class="btn btn-primary btn-user btn-block" type="submit">Let's Begin</button>
                      <hr>
                      {% comment %}
                      <!-- <a href="{% url 'social:begin' 'facebook' %}" class="btn btn-facebook btn-user btn-block">
                        <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook
                      </a> -->
                      {% endcomment %}
                      <script type="text/javascript">
                          $(function(){
                              $(".alert-message").alert();
                              $('#mainForm').submit(function(){
                                  $('#submit').button('loading');
                              })
                          });
                          document.forms[1].elements[2].focus();
                      </script>
                      {% endbuttons %}
                    </form>
                    <div class="text-center text-white ">
                      <a class="small text-white" href="{% url 'users:password_reset' %}">Reset Password</a>
                    </div>

                    <div class="text-center text-white">
                      <a class="small text-white" href="{% url 'users:signup_user' %}">Create an Account!</a>
                    </div>
                    <div class="text-center text-white py-3">
                      <p class="m-0 text-center text-dark">Copyright © 2019</p>
                    </div>

                  </div>
                </div>
              <!-- </div> -->
            </div>
          </div>
        </div>
    </div>

  </div>
</div>
{% endblock %}

olive_app/templates/users/password_reset_complete.html
{{% extends 'users/base_accounts.html' %}
{% load static bootstrap4 %}

{% comment %}
  {% load dashboardconfig %}
{% DashboardConfigs as config %}
{% endcomment %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{% block title %}  Password Reset Complete {% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-4">
            <div class="login-panel panel panel-default">
            <!-- <center><a href="/"><img src="{% if config.site_logo %} {{config.site_logo}} {% else %} https://otextcity.com/images/loggo.png {% endif %}" alt="{{config.site_name}}" title="{{config.site_name}}" width="30%"></a></center> -->
                <div class="panel-heading">
                    <center>
                        <h3 class="panel-title"> 
                            Your password has been set. You may go ahead and <a href="{% url 'users:user_login' %}">login in</a> now.
                        </h3
                    ></center>
                </div>
                
            </div>
        </div>
    </div>
</div>
 <div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-12 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image">
              </div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <a href="/"><img src="https://otextcity.com/images/loggo.png" alt="Otextcity" title="Otextcity" width="30%"></a>
                    <h1 class="h4 text-gray-900 mb-4">Reset Pasword!!!</h1>
                  </div>
                  <p>
                  Your password has been set. You may go ahead and <a href="{% url 'users:user_login' %}">login in</a> now.
                  </p>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="{% url 'users:signup_user' %}">Register</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>
{% endblock %}

olive_app/templates/users/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your {{ user.get_username }} Otextcity Account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,

Otextcity!!!
{% endautoescape %}

olive_app/templates/users/password_reset_form.html
{% extends 'users/base_accounts.html' %}
{% load static bootstrap4 %}

{% comment %}
  {% load dashboardconfig %}
{% DashboardConfigs as config %}
{% endcomment %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{% block title %}  Password Reset {% endblock %}
{% block content %}
<style>
  body{
    background-image:url({% static 'images/3cogs.png' %});
    background-size: 100px 100px;
  }
  .card{
    background-color: #fffffff1!important;
  }
</style>

 <div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-6 col-lg-6 col-md-6">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-12">
                <div class="p-5">
                  <div class="text-center">
                    <!-- {% if config.site_logo %}<a href="/"><img src="{{config.site_logo.url}}" alt="{{config.site_name}}" title="{{config.site_name}}" width="30%"></a>{% endif %} --> -->
                    <h1 class="h4 text-gray-900 mb-4">Reset Pasword!!!</h1>
                    <p>We get it, stuff happens. Just enter your email address below and we'll send you a link to reset your password!
                    </p>
                  </div>
                  <form id="mainForm" class="user" role="form" method="post">
                    {% csrf_token %}                        
                        {% bootstrap_form form %}
                        {% buttons %}
                        <button id="submit" class="btn btn-lg btn-success btn-user btn-block" type="submit">Reset</button>
                        <script type="text/javascript">
                            $(function(){
                                $(".alert-message").alert();
                                $('#mainForm').submit(function(){
                                    $('#submit').button('loading');
                                })
                            });
                            document.forms[1].elements[2].focus();
                        </script>
                        {% endbuttons %}
                  </form>
                  <hr>
                    <div class="text-center text-dark">
                      <a class="small" href="{% url 'users:user_login' %}">Login</a>
                    </div>

                    <div class="text-center">
                      <a class="small" href="{% url 'users:signup_user' %}">Create an Account!</a>
                    </div>
                    <div class="text-center text-white py-3">
                      <p class="m-0 text-center text-dark">Copyright © 2019</p>
                    </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

    <!-- jQuery -->
{% endblock %}

olive_app/templates/users/register.html
{% extends 'users/base_accounts.html' %}
{% load static bootstrap4 %}

{% comment %}
  {% load dashboardconfig %}
{% DashboardConfigs as config %}
{% endcomment %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{% block title %}  Register {% endblock %}
{% block content %}
<style>
  body{
    background-image:url({% static 'images/3cogs.png' %});
    background-size: 100px 100px;
  }
  .card{
    background-color: #fffffff1!important;
  }
</style>

  <div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-6 col-lg-6 col-md-6">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-12">
                <div class="p-5">
                  <div class="text-center">
                    <!-- {% if config.site_logo %}<a href="/"><img src="{{config.site_logo.url}}" alt="{{config.site_name}}" title="{{config.site_name}}" width="30%"></a>{% endif %} -->
                    <h1 class="h4 text-gray-900 mb-4">Create An Account!</h1>
                  </div>
                  <div><p class="text-warning">{{Error}}</p></div>
                  <form id="mainForm" class="form" role="form" method="post">
                    {% csrf_token %} 
          					{% bootstrap_form register_form %}
                    {% buttons %}
                    <button id="submit" class="btn btn-primary btn-user btn-block" type="submit">Register</button>
                    <hr>
                    {% comment %}
                    <!-- <a href="{% url 'social:begin' 'facebook' %}" class="btn btn-facebook btn-user btn-block">
                      <i class="fab fa-facebook-f fa-fw"></i> Register with Facebook
                    </a> -->
                    {% endcomment %}
                    <script type="text/javascript">
                        $(function(){
                            $(".alert-message").alert();
                            $('#mainForm').submit(function(){
                                $('#submit').button('loading');
                            })
                        });
                        document.forms[1].elements[2].focus();
                    </script>
                    {% endbuttons %}
                  </form>
                  {% comment %}
                  <div class="text-center">
                    <a class="small" href="{% url 'user_login:password_reset' %}">Reset Password</a>
                  </div>
                  {% endcomment %}

                  <div class="text-center">
                    <a class="small" href="{% url 'users:user_login' %}">Already Registered? Login!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

{% endblock %}